name: work_report
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^4.4.1
  connectivity_plus: ^2.2.1
  google_fonts: ^2.3.1
  asuka: ^2.0.0
  dio: ^4.0.4
  flutter_dotenv: ^5.0.2
  flutter_secure_storage: ^5.0.2
  jwt_decoder: ^2.0.1
  equatable: ^2.0.3
  validatorless: ^1.2.1
  intl: ^0.17.0
  image_picker: ^0.8.4+11
  http_parser: ^4.0.0
  photo_view: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
